name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30'
          
      - name: Build APK
        run: ./gradlew assembleRelease
        
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-apk
          path: app/build/outputs/apk/release/app-release.apk
